### ISSUE TITLE
sudo chown $USER /data/db CONSIDERED HARMFUL

### ISSUE THREAD

**Issue by bgveenstra** [SF-WDI-LABS/installfest#16]
A student accidentally ran this command as 

sudo chown $USER / data/db

This caused the error message:
    
sudo: /etc/sudoers is owned by uid 501, should be 0
sudo: no valid sudoers sources found, quitting

It also made it impossible for him to restart his computer into macOS - the restart would hang at the apple + loading bar logo. 

It was possible for him to enter single user mode.

**Comment by mnfmnfm** [comment]
Seems to have been fixed by forcing students to `cd /` first, so they have no leading slashes.
