### ISSUE TITLE
running tree command from root directory is a No Bueno

### ISSUE THREAD

**Issue by nathanallen** [SF-WDI-LABS/installfest#21]
perhaps add a depth flag (`-l`?) or `ctrl +  c` reminder.

**Comment by justincastilla** [comment]
Is there any npm package we can download that is more useful and can be checked just as quickly?

**Comment by nathanallen** [comment]
All in favor of removing `tree` from installfest, please 👍. @justincastilla @bgveenstra @mnfmnfm @cofauver @jeanmw
