### ISSUE TITLE
must open Atom after installation in order for `apm` command to be available in shell

### ISSUE THREAD

**Issue by nathanallen** [SF-WDI-LABS/installfest#9]

**Comment by nathanallen** [comment]
@iliastsangaris @cofauver Please be aware that you have erroneously closed https://github.com/SF-WDI-LABS/installfest/issues/9 with https://github.com/sf-wdi-31/installfest/issues/9 when you merged. You must reference your **repo** AND **issue** when closing issues.

I would encourage you to do ALL issue tracking on SF-WDI-LABS.

**Comment by ilias-t** [comment]
Good to know, more info on that [here](https://help.github.com/articles/autolinked-references-and-urls/#issues-and-pull-requests)

**Comment by mnfmnfm** [comment]
Closing, as we no longer recommend using apm.
